### ISSUE TITLE
Transfer Error in TestNet

### ISSUE THREAD

**Issue by kuruharbi** [xeroc/python-bitshares#11]
When I use "wss://node.bitshares.eu" (live node)
```
from bitshares import BitShares
bitshares = BitShares()
bitshares.wallet.unlock("secret word")
bitshares.transfer("red-head", "1", "BTS","memo details here",None)  --> **This is working**
```
When I use "wss://node.testnet.bitshares.eu" (testnet node)
```
from bitshares import BitShares
bitshares = BitShares()
bitshares.wallet.unlock("secret word")
bitshares.transfer("red-head", "1", "TEST","memo details here",None)  --> **This is NOT WORKING**
```
Here is the error details ;

> Traceback (most recent call last):
>   File "/home/serdar/bitshares-deneme.py", line 46, in <module>
>     print(bitshares.transfer("testt1", "1", "MYBTC","deneme",None))
>   File "/home/serdar/.local/lib/python3.5/site-packages/bitshares/bitshares.py", line 429, in transfer
>     "prefix": self.rpc.chain_params["prefix"]
>   File "/home/serdar/.local/lib/python3.5/site-packages/bitsharesbase/operations.py", line 46, in __init__
>     memo = Optional(Memo(kwargs["memo"]))
>   File "/home/serdar/.local/lib/python3.5/site-packages/bitsharesbase/objects.py", line 98, in __init__
>     ('from', PublicKey(kwargs["from"], prefix=prefix)),
>   File "/home/serdar/.local/lib/python3.5/site-packages/bitsharesbase/account.py", line 84, in __init__
>     super(PublicKey, self).__init__(*args, **kwargs)
>   File "/home/serdar/.local/lib/python3.5/site-packages/graphenebase/account.py", line 216, in __init__
>     self._pk = Base58(pk, prefix=prefix)
>   File "/home/serdar/.local/lib/python3.5/site-packages/graphenebase/base58.py", line 60, in __init__
>     raise ValueError("Error loading Base58 object")
> ValueError: Error loading Base58 object

**Comment by kuruharbi** [comment]
`bitshares.transfer("<to>", "<amount>", "<asset>", "[memo]", account="<from>")`

In testnet I can use `bitshares.transfer` without problem If [memo] variable is = None
but when I set [memo] varialble as a string of some value ,then I get the error I mentioned above

**Comment by xeroc** [comment]
Thanks for the report .. this clearly is a bug

**Comment by anthon-alindada** [comment]
@xeroc Any news/fixes on this bug?

**Comment by tximiss** [comment]
I keep waiting for updates. Nice to hear it is a bug.

**Comment by JanusChoi** [comment]
Seems like piston also has this bug...

**Comment by tximiss** [comment]
This bug is only for TestNet? Anybody gave a try in real?

**Comment by kuruharbi** [comment]
This bug is only for testnet

**Comment by xeroc** [comment]
If fixed this in `develop` branch .. can someone try?

**Comment by tximiss** [comment]
With develop branch i get:

  File "/usr/local/lib/python3.5/dist-packages/bitshares/bitshares.py", line 442, in transfer
    "memo": memoObj.encrypt(memo),
  File "/usr/local/lib/python3.5/dist-packages/bitshares/memo.py", line 66, in encrypt
    prefix=self.bitshares.rpc.chain_params["prefix"]
  File "/usr/local/lib/python3.5/dist-packages/bitsharesbase/account.py", line 84, in __init__
    super(PublicKey, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/graphenebase/account.py", line 216, in __init__
    self._pk = Base58(pk, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/graphenebase/base58.py", line 60, in __init__
    raise ValueError("Error loading Base58 object")
ValueError: Error loading Base58 object

**Comment by zhangpanyi** [comment]
I also met this mistake

**Comment by xeroc** [comment]
That was a stupid one :-(

```
from bitshares import BitShares
bitshares = BitShares("wss://node.testnet.bitshares.eu")
from getpass import getpass
bitshares.wallet.unlock(getpass())
bitshares.transfer("faucet", 1, "TEST", "memo")
```
Now works

**Comment by darkmaycal** [comment]
>> from bitshares import BitShares
>>> bitshares = BitShares("wss://node.testnet.bitshares.eu")
>>> from getpass import getpass
>>> bitshares.wallet.unlock(getpass())
Password: pass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\graphenecommon\wallet.py", line 104, in unlock
    return self.store.unlock(pwd)
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\graphenestorage\masterpassword.py", line 91, in unlock
    self._decrypt_masterpassword()
  File "C:\Users\User\AppData\Roaming\Python\Python37\site-packages\graphenestorage\masterpassword.py", line 106, in _decrypt_masterpassword
    self._raise_wrongmasterpassexception()
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\graphenestorage\masterpassword.py", line 111, in _raise_wrongmasterpassexception
    raise WrongMasterPasswordException
graphenestorage.exceptions.WrongMasterPasswordException
>>>
How to create wallet on Windows python?
