### ISSUE TITLE
import backup file

### ISSUE THREAD

**Issue by guanqun** [xeroc/python-bitshares#12]
This could be a silly question, I have a wallet backup file, how can I import that into the pybitshares wallet? I searched the code, but didn't find anything related to "restore" or something, could you help shed some light on this?

**Comment by xeroc** [comment]
pybitshares doesn't currently support the format used by the web wallet. Sorry

**Comment by guanqun** [comment]
Thanks for the clarification. Is there any way to workaround this? e.g. extract the key from the wallet and then import the key to pybitshares?

Is this web wallet's format a standard format? If it's simple enough, I can help add that support.

sorry for lots of questions. new to this area.

**Comment by xeroc** [comment]
You can manually obtain your private keys from the "permissions" tab of your account and clicking the public ckey. Then you can import your private key with

    uptick addkey

The web wallet's format is somewhat standard as the UI uses it heavily. No other implementation can import that format so far. It is also (unfortunately) only little documented

**Comment by guanqun** [comment]
I finally figured this out :) Thanks anyway.
