### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by deverick** [xeroc/python-bitshares#2]
1. There is no link to this github repo in the documentation.  I suggest it at least needs to be on this page: http://docs.pybitshares.com/en/latest/contribute.html
2. There is no help or support page.  The support info is bundled into the contribute page.  I suggest a new help page with suggestions to use community channels for general assistance and the github repo issue function for reporting bugs. help page menu link should always be visible on the left
3. The wallet and storage object documentation needs to be enhanced as this area is confusing for newbies.  need explicit examples on how to add a new pub/wif.  a description about how it works would help, is the account name is not stored locally?  also a description where this key info could be sourced would be helpful, a bit like the btsbots explanation of where the keys are found in the online exchange (screenshots would be great here too.
Great effort so far, keep up the good work!

**Comment by AdityaSoni19031997** [comment]
Its true

**Comment by xeroc** [comment]
The only thing that I couldn't get running right away is the request to have a support link in the menu on the left hand side. The docs page is autogenerated through sphinx and I would need to change the whole templating stuff to get there.
