### ISSUE TITLE
Selecting asset for paying fee's

### ISSUE THREAD

**Issue by anthon-alindada** [xeroc/python-bitshares#22]
I've tried building a transaction where i set the asset fee for transfer but it's still using 1.3.0(BTS) for the fee. Can someone help me with this. Here's the code i'm using.

```
from bitshares.transactionbuilder import TransactionBuilder
from bitsharesbase.operations import Transfer
tx = TransactionBuilder()
tx.appendOps(Transfer(**{
    "fee": {"amount": 0, "asset_id": "1.3.121"},
    "from": "1.2.124",
    "to": "1.2.1241",
    "amount": {"amount": 500, "asset_id": "1.3.121"},
}))
tx.appendSigner("xeroc", "active")
tx.sign()
tx.broadcast()
```

Am i doing it wrong? If so please show me how to set asset fee thank you.

**Comment by xeroc** [comment]
python bitshares currently does not support paying fees in assets other than BTS .. sorry

**Comment by anthon-alindada** [comment]
Hi @xeroc, how can i contribute in putting that feature in the library? What library should i look up? The python-graphene or the python-bitshares? And also i have a separate question with fees, Why does the fee gets bigger the bigger the memo is? Thank you.

**Comment by xeroc** [comment]
python-bitshares makes use of python-graphene .. so I recommend you stick with python-bitshares.

for this feature, we would need to modify the transactionbuilder:
[Here](https://github.com/xeroc/python-bitshares/blob/master/bitshares/transactionbuilder.py#L272) it adds the fee. The call itself can handle a second parameter to define the asset_id to pay the fee in (see [here](https://github.com/xeroc/python-bitshares/blob/master/bitsharesbase/transactions.py#L22))

Unfortunately, I currently don't have that much time to deal with this ..

But this is what I would do:
modify the Transaction builder to accept an additional parameter (`kwargs`), similar to `proposer` and deal with the variable when calling addRequiredFees.

Looking forward to see Pull Requests coming in.

**Comment by xeroc** [comment]
> Why does the fee gets bigger the bigger the memo is?

That's what the blockchain asks for .. not the library.
