### ISSUE TITLE
Add buyer/seller user IDs to 'get_trade_history' ?

### ISSUE THREAD

**Issue by grctest** [xeroc/python-bitshares#27]
The buyer & seller's user identities [were added to the 'get_trade_history' command within Bitshares-core](https://github.com/bitshares/bitshares-core/issues/329#issuecomment-319718090) recently, however this information is not retrieved using `Market("USD:BTS").trades()`.

Could this be added to the above Python function so that we can establish who the true market makers are within the BTS DEX with fewer commands than currently neccessary?

Prupose: Establish new ShareDropping vector.

Thanks 👍

**Comment by xeroc** [comment]
the `get_trade_history` doesn't expose that id unfortunately, that's why pybitshares doesn't have it either.

**Comment by xeroc** [comment]
scratch that .. I saw that Alfredo added it .. working on this now
