### ISSUE TITLE
Transfer Error

### ISSUE THREAD

**Issue by kuruharbi** [xeroc/python-bitshares#3]
When I try to use transfer function if I set memo parameter as None it is sending successfully
But If set memo parameter as a string I am getting this error output ;

from bitshares import BitShares
bitshares = BitShares()
bitshares.wallet.unlock("xxxxxxxx")
bitshares.transfer("red-head2", "0.000001", "OPEN.BTC", None,"red-head") --> this is working good
bitshares.transfer("red-head2", "0.000001", "OPEN.BTC", "sometextmessage","red-head") --> this is NOT working

Error Details
Traceback (most recent call last):
  File "/home/serdar/bitshares-deneme.py", line 39, in <module>
    bitshares.transfer("red-head2", "0.000001", "OPEN.BTC", "[<memo>]","red-head")
  File "/home/serdar/.local/lib/python3.5/site-packages/bitshares/bitshares.py", line 422, in transfer
    "memo": memoObj.encrypt(memo)
  File "/home/serdar/.local/lib/python3.5/site-packages/bitsharesbase/operations.py", line 45, in __init__
    memo = Optional(Memo(kwargs["memo"]))
  File "/home/serdar/.local/lib/python3.5/site-packages/bitsharesbase/objects.py", line 98, in __init__
    ('from', PublicKey(kwargs["from"], prefix=prefix)),
KeyError: 'from'

**Comment by xeroc** [comment]
The `account=` attribute in the call is not required. It will obtain the account from the configuration's `default_account`.

If you want to send from a specific account in your wallet you need to provide it explicitly with `account=` like this:

    bitshares.transfer("red-head2", "0.000001", "OPEN.BTC", "sometextmessage",account="red-head")

**Comment by kuruharbi** [comment]
I can send asset when I set memo parameter as None, 
But my main problem is when I try to set memo parameter with some text data it is giving the same error like above.
I can not send asset with memo details...
Please could you help to fix that problem?

**Comment by kuruharbi** [comment]
![image](https://cloud.githubusercontent.com/assets/26321769/25042443/c0e116a4-2120-11e7-80dd-aa3bd935b5a9.png)

I want to send like that, I want to write memo text...

**Comment by xeroc** [comment]
Thanks for the report. This was in fact an error I made in the code. Has been fixed in the `develop` branch and will be available in the next release
