### ISSUE TITLE
Can't use multithreading to buy

### ISSUE THREAD

**Issue by Daice** [xeroc/python-bitshares#34]
`Traceback (most recent call last):`
  `File "/home/daiz/.local/lib/python3.5/site-packages/bitshares-0.1.9-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 42, in rpcexec`
 ` File "/home/daiz/.local/lib/python3.5/site-packages/graphenelib-0.5.5-py3.5.egg/grapheneapi/graphenewsrpc.py", line 160, in rpcexec`
`grapheneapi.graphenewsrpc.RPCError: Assert Exception: operations.size() > 0: A transaction must have at least
one operation`

**Comment by xeroc** [comment]
Sorry about that, but the `TransactionBuilder` is not multithread-compatible because it uses static/class variables. Same with the Wallet. I don't yet know of an efficient and easy way to make those multithreading compatible
