### ISSUE TITLE
Calling account.openorders gives the original order

### ISSUE THREAD

**Issue by mikakoi** [xeroc/python-bitshares#38]
Calling account.openorders gives orders that have the original details.
For example if I make a sell order with amount of 20, and somebody buys half of that, account.openorders still returns the original 20 as amount.

Is there another method to get the updated amount?

**Comment by xeroc** [comment]
just call `account.refresh()`

**Comment by mikakoi** [comment]
Calling account.refresh doesn't seem to do what you claim. The problem seems to be in the Order class. When the super constructor is called, it's given the value of sell_price key in args which doesn't include the updated amount of the order. args does have for_sale key (Which has the updated amount) but is never used.

**Comment by xeroc** [comment]
Oh ... do you mean it is a problem of [Order()](https://github.com/xeroc/python-bitshares/blob/master/bitshares/price.py#L399). That class (IIRC) does indeed not use `for_sale`.
Do you mind patching it and sending a pull request the way you would like it to be?
