### ISSUE TITLE
change the markets/accounts a Notify listens to on-the-fly

### ISSUE THREAD

**Issue by ihaywood3** [xeroc/python-bitshares#42]
I need to be able to change the events a Notify subscriptions to without reloading, so multiple bots can be started/stopped while running in one thread
(Currently the solution is to have each bot run in  its own thread with its own Notify instance and socket connection: not very kind to the public witness node)
[reset-notify.diff.txt](https://github.com/xeroc/python-bitshares/files/1733345/reset-notify.diff.txt)

**Comment by xeroc** [comment]
thanks for the patch!
