### ISSUE TITLE
Memo class not in bitsharesbase.memo.py

### ISSUE THREAD

**Issue by gdfbacchus** [xeroc/python-bitshares#5]
Tried following the documentation [here](http://docs.pybitshares.com/en/latest/memo.html) and got this error:
![image](https://cloud.githubusercontent.com/assets/12011932/25730317/9e05472e-3109-11e7-8483-97f2199e2786.png)
After looking at the memo.py file I see that the Memo class is never created.

**Comment by xeroc** [comment]
The `Memo` class is in `bitshares.memo`.
the memo in `bitsharesbase` is low-level stuff.
I'll fix the docs asap
