### ISSUE TITLE
Unhandled RPC error w/ dacplay ws server

### ISSUE THREAD

**Issue by grctest** [xeroc/python-bitshares#53]
I was recently investigating the cause of an internal server error in the hug-rest api: https://github.com/BTS-CM/Bitshares-HUG-REST-API/issues/2

The script would occasionally fail at this point:
```
 price = market.ticker()["quoteSettlement_price"] # Get Settlement price of USD
```

It appears to only trigger against the following server:
```
Server: wss://bitshares.dacplay.org/ws
Traceback (most recent call last):
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 42, in rpcexec
    return super(BitSharesNodeRPC, self).rpcexec(payload)
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 160, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: Assert Exception: _index[space_id].size() > type_id:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 44, in <module>
    print(market.ticker())
  File "/home/btsapi/python-bitshares/bitshares/market.py", line 154, in ticker
    self["quote"]["id"],
  File "/home/btsapi/HUG/lib/python3.6/site-packages/grapheneapi/graphenewsrpc.py", line 195, in method
    r = self.rpcexec(query)
  File "/home/btsapi/python-bitshares/bitsharesapi/bitsharesnoderpc.py", line 50, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _index[space_id].size() > type_id:
```

It's not caused due to the server being unreachable, as the following works:
```
Lost connection to node during wsconnect(): wss://bitshares.crypto.fans/ws (2/-1
```

Is this caused by the dacplay server not having required extensions enabled? To deter this from happening again, would it be wise to add try/except handling to all RPC attempts in the code?

In the mean time, I've removed the dacplay server from my API.

Cheers 👍

**Comment by xeroc** [comment]
That error tells me that they disabled some of their APIs or plugins so that a query for something fails. I'd guess they don't have the markethistory plugin enabled on their API node

**Comment by grctest** [comment]
@xeroc Is there any way to detect the capabilities of a full node so as to prevent this uncaught exception triggering again? Like a plugin capability handshake? Or just better to remove entry from node list?

Cheers 👍

**Comment by ThomasFreedman** [comment]
I'm curious why you coded the "UnhandledRPCError" exception the way you did. It makes it difficult to handle those errors (they aren't "caught" by a generic except clause)

**Comment by xeroc** [comment]
> @xeroc Is there any way to detect the capabilities of a full node so as to prevent this uncaught exception triggering again? Like a plugin capability handshake? Or just better to remove entry from node list?

I don't believe so.

> I'm curious why you coded the "UnhandledRPCError" exception the way you did. It makes it difficult to handle those errors (they aren't "caught" by a generic except clause for example)

I could add support for a more meaningful error in this particular case, but it may not necessrily only be caused by a missing plugin ..

**Comment by ThomasFreedman** [comment]
That's fine if you want to do that, but still curious as you didn't actually answer the question I posed.
I suspect you had a good reason for coding the exception that way, I just don't understand why it isn't "catchable". It's like you don't want people to ignore it and you want a fatal error in all cases. What am I missing? Why make this exception impossible to handle? If it `can` be handled, 1) why make doing so difficult, 2) could you provide an example of how to trap for it?

Thanks Fabian!
