### ISSUE TITLE
Historic settlement prices?

### ISSUE THREAD

**Issue by grctest** [xeroc/python-bitshares#55]
Hey,

Would it be possible to request historical market data through python-bitshares in the future?

Like:
```
market = Market("USD:BTS", "2018-03-01T12:00:00+00:00")
historical_ticker_data = market.ticker()
```

Would this require changes to bitshares-core to achieve?

The second best solution for retrieving the feed price for an asset would be using elastic search to retrieve published price feeds (from a single user, rather than asset-summary data?) for the asset in question, probably the simpler solution?

**Comment by xeroc** [comment]
This data is not available from the API, so i cannot provide it in pybitshares :-(
There currently really is no way of obtaining that data

**Comment by grctest** [comment]
Looks like we're able to get it via the inbuilt ES, is that out of scope of python-bitshares? https://github.com/bitshares/bitshares-core/issues/690#issuecomment-378634339

**Comment by xeroc** [comment]
So far, python-bitshares does not (yet) interact with ES ... I plan to add this in the future but .. time ..
