### ISSUE TITLE
Is there a api to get historical price data in bitshares DEX?

### ISSUE THREAD

**Issue by testmana2** [xeroc/python-bitshares#7]
Hello,
Is there a api to get historical price data in bitshares DEX?
Just like the https://bitshares.org/wallet/#/market/OPEN.BTC_USD kline chart data with OHLC and volume data.

Thank you for your excellent api library.

**Comment by xeroc** [comment]
Take a look at how [`uptick trades OPEN.BTC:USD`](https://github.com/xeroc/uptick/blob/master/uptick/markets.py#L40-L56) works.

**Comment by AsoSun** [comment]
Hi, but the volume method does not support time argument, how can I get the historical volume data?

**Comment by tximiss** [comment]
Try with rpc call:
`Bitshares.rpc.get_trade_history("BTS", "CNY", t.isoformat(), f.isoformat(), 100)`

**Comment by AsoSun** [comment]
Hey, thanks, rpc.get_trade_history works. However, Is there anyway to obtain the market price history data? I don’t see any method in this python API .

**Comment by tximiss** [comment]
There is no price stored, only transactions in the forms accountJ wants N assetX for M assetY.
The price for assetX is M/N assetY and the price for assetY is N/M assetX.
Is the way Bitshares works, and any asset could be traded with whatever asset.

**Comment by AsoSun** [comment]
Hi, I know that the bitshares1-core has method
blockchain_market_price_history to get access the history OHLCV data
(however I don’t know how to implement this method...) do we have similar
method in this python API, or if you know how to implement this method ?
Thanks

**Comment by AsoSun** [comment]
Hi, I know that the bitshares1-core has method blockchain_market_price_history to get access the history OHLCV data (however I don’t know how to implement this method...) do we have similar method in this python API, or if you know how to implement this method ? Thanks

**Comment by tximiss** [comment]
As far i know there is not such method available.

**Comment by xeroc** [comment]
OHLCV data is available through `Market("BTS:USD").trades()`.
See for instance how uptick works: https://github.com/xeroc/uptick/blob/master/uptick/markets.py#L40-L56
